项目列表页英文翻译 #189
wuhan2020/wuhan2020.github.io pull request #213
Opened 2020-02-12 05:51 UTC by anndawn

项目列表页英文翻译 #189

2020-02-12 06:01 UTC, GindaChen requested changes
Thanks for the contribution! Some direct translation might not work here. It would be great if you can consider tailoring the text for English reader - also other English-as-second-language readers. 
But anyways - thanks for contribution! Love to hear back from you

2020-02-12 06:01 UTC, GindaChen commented on site_config/project.js
> +                  title: '2020 Support Wuhan',
Hmm... I'm not sure this is the good translation. Something like
```
2020 Wuhan Rescue
```
would sound better

2020-02-12 06:01 UTC, GindaChen commented on site_config/project.js
> +                    title: 'Wuhan New Coronavirus Outbreak Prevention Information Collection Platform',
**Novel**
```
Wuhan Novel Coronovirus Outbreak
```
is the previous name.

2020-02-12 06:01 UTC, GindaChen commented on site_config/project.js
> +                  description: 'Establish a real-time data service with information on hospitals, factories and procurement. Convene everyone who wishes to contribute to this battle against coronavir
- realtime **data service platform**
- Convene -> Convey? Connect?

2020-02-12 06:01 UTC, GindaChen commented on site_config/project.js
> +                  description: '2019-nCoV navigation site provides the public with a convenient and comprehensive information portal as well as systematically organize all online resources and useful
Suggest change
```
2019-nCoV navigation site provides the public with a convenient and comprehensive information portal as well as systematically organize all online resources and useful channels related to 2019-nCoV.
```
to
```
2019-nCoV navigation site is a information portal with online resources and archival information related to 2019-nCoV.```

Direct translation will not work here.

2020-02-12 06:01 UTC, GindaChen commented on site_config/project.js
> +                  description: 'Wuhan2020 community official website, convene volunteers all over the world from different backgrounds to establish an open-source information system and contribute to
Same as above.

2020-02-12 17:36 UTC, iLtc commented on site_config/project.js
> +                  title: '2020 Support Wuhan',
I personally think "rescue" is too scary.

2020-02-13 05:33 UTC, anndawn commented on site_config/project.js
> +                  description: '2019-nCoV navigation site provides the public with a convenient and comprehensive information portal as well as systematically organize all online resources and useful
how about keeping convenient and comprehensive?

2020-02-13 05:34 UTC, anndawn commented on site_config/project.js
> +                    title: 'Wuhan New Coronavirus Outbreak Prevention Information Collection Platform',
√

2020-02-13 05:39 UTC, anndawn commented on site_config/project.js
> +                  description: 'Wuhan2020 community official website, convene volunteers all over the world from different backgrounds to establish an open-source information system and contribute to
Wuhan 2020 community calls for volunteers from all over the world to establish an open-source information platform and contribute to battling the 2019-nCoV.
is this okay?

2020-02-13 05:45 UTC, anndawn commented on site_config/project.js
> +                  description: 'Establish a real-time data service with information on hospitals, factories and procurement. Convene everyone who wishes to contribute to this battle against coronavir
agree on data service platform.  How about this?
Our goal is to establish a real-time data service platform with information on hospitals, factories and procurement, allowing anyone with relevant skills to participate in this initiative. We would like to call for anyone who wishes to contribute to this battle against coronavirus to join us.

2020-02-13 05:54 UTC, GindaChen commented on site_config/project.js
> +                  title: '2020 Support Wuhan',
I agree - I just don't know what's better...

2020-02-13 05:54 UTC, GindaChen commented on site_config/project.js
> +                  description: '2019-nCoV navigation site provides the public with a convenient and comprehensive information portal as well as systematically organize all online resources and useful
Yep - go for it

2020-02-13 05:55 UTC, GindaChen commented on site_config/project.js
> +                  description: 'Wuhan2020 community official website, convene volunteers all over the world from different backgrounds to establish an open-source information system and contribute to
`battling` ... sounds weird. `combat` will be grammatically correct but too political.
`open source platform related to 2019-nCoV` should be okay?

2020-02-13 07:34 UTC, merged