add ncov-project-introduced.md, fix #227
wuhan2020/wuhan2020.github.io pull request #270
Opened 2020-02-19 01:45 UTC by jeremy0519

2020-02-19 02:20 UTC, lovepoem requested changes
title 为 开源共抗：疫情信息导航站点正式入驻wuhan2020开源社区

其他关键字相应修改

还有在i18n的社区地方加上导航

2020-02-19 02:22 UTC, lovepoem commented on blog/zh-cn/nav-project-introduced.md
> +title: 如何加入到 Wuhan2020 开源项目，打赢这场没有硝烟的战争？
修改

2020-02-19 02:52 UTC, jeremy0519 commented
keywords写什么？

2020-02-19 02:59 UTC, jeremy0519 commented
还有发布时间写什么，网页上写的是1周前，到底是几月几号？

2020-02-20 00:52 UTC, jeremy0519 commented
@lovepoem

2020-02-20 01:16 UTC, lovepoem commented on blog/zh-cn/nav-project-introduced.md
> +---
问题没有解决呀，这个title是是一篇老文章的seo设置，你要修改成这篇自己的

2020-02-20 01:20 UTC, jeremy0519 commented on blog/zh-cn/nav-project-introduced.md
> +---
我想问的是keywords和发布时间写什么？网页上写的是1周前，到底是几月几号？

2020-02-20 01:32 UTC, jeremy0519 commented on blog/zh-cn/nav-project-introduced.md
> +---
@lovepoem

2020-02-20 02:19 UTC, jeremy0519 commented
还差keywords

2020-02-20 02:25 UTC, jeremy0519 commented
keywords我挑了两个

2020-02-20 02:56 UTC, jeremy0519 commented
@lovepoem

2020-02-20 03:13 UTC, merged